import { useEffect, useState } from 'react';
import { Activity, ArrowRight, BadgeCheck, BarChart3, Bell, BriefcaseBusiness, Check, ChevronRight, Clock3, Droplets, Hammer, IndianRupee, LayoutDashboard, MapPin, ShieldCheck, Sparkles, Star, Users, Wrench, Zap } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const API = 'http://localhost:8000';
const nav = [{id:'customer', label:'Customer', icon: Wrench}, {id:'worker', label:'Worker desk', icon: BriefcaseBusiness}, {id:'cooperative', label:'Cooperative', icon: LayoutDashboard}];

function App() {
  const [view, setView] = useState('customer');
  const [match, setMatch] = useState(null);
  const [job, setJob] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dashboard, setDashboard] = useState(null);
  const [request, setRequest] = useState({ service_type:'Plumbing', description:'Bathroom pipe is leaking', area:'Area A', latitude:12.9716, longitude:77.5946, urgency:'emergency' });

  useEffect(() => { fetch(`${API}/cooperative/dashboard`).then(r => r.json()).then(setDashboard).catch(() => {}); }, [job]);
  const runMatch = async (event) => { event?.preventDefault(); setLoading(true); const response = await fetch(`${API}/service-request`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(request)}); setMatch(await response.json()); setLoading(false); };
  const accept = async () => { const response = await fetch(`${API}/accept-job/${match.request_id}`, {method:'POST'}); setJob(await response.json()); setView('worker'); };
  const advance = async () => { const endpoint = job.status === 'assigned' ? 'start-job' : 'complete-job'; const response = await fetch(`${API}/${endpoint}/${job.job_id}`, {method:'POST'}); setJob(await response.json()); };
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Hammer size={20}/></div><div><strong>HANDYMAN</strong><span>COOPERATIVE NETWORK</span></div></div><div className="side-label">Workspace</div><nav>{nav.map(({id,label,icon:Icon}) => <button className={view===id?'nav-item active':'nav-item'} onClick={() => setView(id)} key={id}><Icon size={18}/>{label}<ChevronRight size={15}/></button>)}</nav><div className="sidebar-bottom"><div className="status-dot"><span/> System operational</div><small>Smart work. Fair opportunities.<br/>Stronger communities.</small></div></aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">BENGALURU COOPERATIVE / 11 SEPT 2026</span><h1>{view === 'customer' ? 'Request a helping hand' : view === 'worker' ? 'Worker command centre' : 'Cooperative intelligence'}</h1></div><div className="top-actions"><button className="icon-button"><Bell size={18}/><i/></button><div className="profile"><div className="avatar soft">AR</div><span>Ananya Rao</span></div></div></header>{view === 'customer' && <Customer request={request} setRequest={setRequest} runMatch={runMatch} loading={loading} match={match} accept={accept}/>} {view === 'worker' && <Worker job={job} advance={advance} />} {view === 'cooperative' && <Cooperative dashboard={dashboard}/>}</main>
  </div>
}

function Customer({request,setRequest,runMatch,loading,match,accept}) { return <div className="content-grid"><section className="hero-panel"><div className="hero-copy"><span className="pill accent"><Sparkles size={14}/> Explainable allocation</span><h2>Household help,<br/><em>cooperatively delivered.</em></h2><p>Tell us what needs attention. Our intelligence engine balances skill, availability, urgency, distance and fair opportunity.</p><div className="metric-row"><div><strong>40+</strong><span>verified workers</span></div><div><strong>6</strong><span>service categories</span></div><div><strong>4.8</strong><span>average rating</span></div></div></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="visual-card"><Droplets size={28}/><strong>Emergency<br/>plumbing</strong><span>Response network ready</span></div><div className="visual-tag"><Activity size={15}/> 92% coverage today</div></div></section><section className="request-card"><div className="section-heading"><div><span className="eyebrow">NEW SERVICE REQUEST</span><h3>What can we fix?</h3></div><span className="step">01 / 03</span></div><form onSubmit={runMatch}><label>Service category</label><div className="service-grid">{['Plumbing','Electrical','Carpentry','Cleaning'].map(item => <button type="button" className={request.service_type===item?'service-option selected':'service-option'} onClick={() => setRequest({...request,service_type:item})} key={item}>{item==='Plumbing'?<Droplets size={17}/>:item==='Electrical'?<Zap size={17}/>:<Wrench size={17}/>}<span>{item}</span>{request.service_type===item&&<Check size={15}/>}</button>)}</div><label>Describe the problem</label><textarea value={request.description} onChange={e=>setRequest({...request,description:e.target.value})}/><div className="form-row"><div><label>Service area</label><select value={request.area} onChange={e=>setRequest({...request,area:e.target.value})}><option>Area A</option><option>Area B</option><option>Area C</option><option>Area D</option></select></div><div><label>Priority</label><div className="priority-toggle"><button type="button" className={request.urgency==='normal'?'':'chosen'} onClick={()=>setRequest({...request,urgency:'normal'})}>Normal</button><button type="button" className={request.urgency==='emergency'?'chosen':''} onClick={()=>setRequest({...request,urgency:'emergency'})}><Zap size={13}/> Emergency</button></div></div></div><button className="primary full" disabled={loading}>{loading?'Finding the best worker...':<>Find my best match <ArrowRight size={17}/></>}</button></form></section>{match && <MatchCard match={match} accept={accept}/>}</div> }

function MatchCard({match,accept}) { const best=match.best_match; if(!best) return <section className="match-card"><h3>No eligible worker found</h3><p>{match.message}</p></section>; return <section className="match-card"><div className="match-top"><div><span className="eyebrow">BEST MATCH FOUND</span><h3>{best.name}</h3><div className="rating"><Star size={16} fill="currentColor"/> 4.8 <span>·</span><BadgeCheck size={16}/> Verified member</div></div><div className="score"><strong>{best.score}</strong><span>/ 100 match</span></div></div><div className="match-meta"><span><Clock3 size={16}/><strong>{best.eta_minutes} min</strong> ETA</span><span><MapPin size={16}/>{best.distance_km} km away</span><span><Users size={16}/>Low workload</span></div><div className="why"><div className="why-title"><Sparkles size={16}/> Why {best.name.split(' ')[0]}?</div>{best.reasons.map(reason=><div className="reason" key={reason}><Check size={15}/>{reason}</div>)}</div><div className="alternatives"><span>Alternatives</span>{match.alternatives.map(item=><div key={item.worker_id}><b>{item.name}</b><span>{item.score} score</span></div>)}</div><button className="primary full" onClick={accept}>Confirm this worker <ArrowRight size={17}/></button></section> }

function Worker({job,advance}) { return <div className="workspace"><div className="welcome-row"><div><span className="eyebrow">RAJESH KUMAR / COOPERATIVE MEMBER</span><h2>Good morning, Rajesh.</h2><p>Your skill passport is active and your opportunity balance is healthy.</p></div><div className="availability"><span className="live-dot"/> Available for work</div></div><div className="stat-grid"><Stat label="Today’s earnings" value="₹1,940" trend="+18% vs last week" icon={IndianRupee}/><Stat label="Completed jobs" value="327" trend="Top 12% in network" icon={Check}/><Stat label="Current workload" value="3 / 8" trend="Healthy capacity" icon={Activity}/></div><div className="two-col"><section className="panel job-panel"><div className="panel-heading"><div><span className="eyebrow">INCOMING ASSIGNMENT</span><h3>{job?'Emergency plumbing request':'No active job yet'}</h3></div>{job?<span className="pill danger"><Zap size={13}/> Emergency</span>:<span className="pill success">Listening</span>}</div>{job?<><div className="job-location"><MapPin size={19}/><div><strong>Area A · Bathroom pipe leak</strong><span>Customer: Ananya Rao · estimated earning ₹680</span></div></div><div className="job-actions"><button className="primary" onClick={advance}>{job.status==='assigned'?'Accept & start service':job.status==='in_progress'?'Complete service':'Service completed'} <ArrowRight size={16}/></button><span className="job-status"><Check size={14}/> {job.status.replace('_',' ')}</span></div></>:<div className="empty-state"><BriefcaseBusiness size={28}/><p>When a customer confirms a match, their job appears here.</p></div>}</section><section className="panel passport"><div className="panel-heading"><div><span className="eyebrow">SKILL PASSPORT</span><h3>Verified capabilities</h3></div><ShieldCheck size={23} className="green"/></div><div className="passport-person"><div className="avatar large">RK</div><div><strong>Rajesh Kumar</strong><span>8 years experience · Member since 2019</span></div></div><div className="tag-list"><span>Plumbing</span><span>Pipe installation</span><span>Water tank repair</span></div><div className="verification"><span><BadgeCheck size={16}/> Identity verified</span><span><BadgeCheck size={16}/> Plumbing Level 2</span></div></section></div></div> }
function Stat({label,value,trend,icon:Icon}) { return <div className="stat-card"><div className="stat-icon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong><small>{trend}</small></div> }

function Cooperative({dashboard}) { if(!dashboard) return <div className="loading-state">Loading cooperative intelligence...</div>; const bars=dashboard.demand; return <div className="workspace"><div className="welcome-row"><div><span className="eyebrow">LIVE NETWORK OVERVIEW</span><h2>See the whole system.</h2><p>Allocation, capacity and fairness in one cooperative view.</p></div><button className="secondary"><Activity size={16}/> Live operations</button></div><div className="stat-grid"><Stat label="Total workers" value={dashboard.workforce.total} trend={`${dashboard.workforce.available} available now`} icon={Users}/><Stat label="Jobs today" value={dashboard.jobs.today} trend={`${dashboard.jobs.completed} completed`} icon={BriefcaseBusiness}/><Stat label="Emergency jobs" value={dashboard.jobs.emergency} trend="Rapid response active" icon={Zap}/><Stat label="Overloaded" value={dashboard.workforce.overloaded} trend="Needs balancing" icon={Activity}/></div><div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">SERVICE DEMAND</span><h3>Requests by category</h3></div><BarChart3 size={21}/></div><ResponsiveContainer width="100%" height={240}><BarChart data={bars}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8e5df"/><XAxis dataKey="service" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="requests" fill="#e76f51" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></section><section className="panel fairness-panel"><div className="panel-heading"><div><span className="eyebrow">WORKLOAD FAIRNESS</span><h3>Opportunity distribution</h3></div><Users size={21}/></div>{dashboard.workload.slice(0,5).map((item,index)=><div className="fair-row" key={item.name}><div className="fair-name"><span className={`rank rank-${index+1}`}>{index+1}</span><b>{item.name}</b><small>{item.area}</small></div><div className="fair-bar"><i style={{width:`${Math.min(100,item.jobs*4)}%`}}/></div><strong>{item.jobs}</strong></div>)}<div className="insight"><Sparkles size={17}/><span><b>Cooperative insight</b> Qualified underutilized workers are available for upcoming jobs.</span></div></section></div><section className="proposal-strip"><div><span className="eyebrow">GOVERNANCE PROTOTYPE</span><h3>Reduce cooperative service allocation from 8% to 6%</h3></div><div className="vote"><strong>72%</strong><span>YES · 28% NO</span></div><button className="secondary">View proposal <ArrowRight size={15}/></button></section></div> }
export default App;
